version: '3'

networks:
  default:
     external:
       name: 'mewe'

services:
  mysql.dnd-mewe.com:
    restart: always
    image: mysql:5.7
    container_name: mysql.dnd-mewe.com
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./user_data:/var/lib/mysql
  mongodb.dnd-mewe.com:
    restart: always
    image: mongo:4.4
    container_name: mongodb.dnd-mewe.com
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ./mewe_data:/data/db
